usuario:
    resource: "@usuarioBundle/Resources/config/routing.yml"
    prefix:   /

tienta:
    resource: "@TientaBundle/Resources/config/routing.yml"
    prefix:   /

ciudad:
    resource: "@CiudadBundle/Resources/config/routing.yml"
    prefix:   /

cupon_oferta:
    resource: "@CuponOfertaBundle/Resources/config/routing.yml"
    prefix:   /

