parameters:
#    cupon_oferta.example.class: Cupon\OfertaBundle\Example

services:
#    cupon_oferta.example:
#        class: %cupon_oferta.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
